### ISSUE TITLE
prnu extarction

### ISSUE THREAD

**Issue by T-nfd** [polimi-ispl/cnn-fast-sdi#3]
Hi,

You'd linked to its source code of PRNU extractor, but I needed help understanding how to use it.
I opened an issue and requested help, but I have yet to receive a reply.
I need to extract PRNU of the Vision dataset to feed my model.
Can you please help me how to apply PRNU extractor code to the Vision dataset?

@smandelli

**Comment by smandelli** [comment]
Hi @T-nfd, I'm closing the issue since you received a reply in the prnu-python repository.

**Comment by T-nfd** [comment]
Dear @smandelli thanks for your reply.
Unfortunately, in practice, I could not work with [example.py](https://github.com/polimi-ispl/prnu-python/blob/master/example.py). I don't understand the code. What I need is how to give the images (batch) to the function and get its PRNU image to feed my model. I was hoping you could help me.

Can you please help me if my code is correct to calculate PRNU? It's based on this formula:
N = I − F (I)
Where N is a noise residual,
I is an input image, and F is a denoising filter

Is the **N** the right thing to feed my model?

**Comment by smandelli** [comment]
Hi @T-nfd, 
to extract the noise residual from an input image, you should use the function provided in prnu-python repository, in particular the function `extract_single` that you can find in `prnu-python/prnu/functions.py`

**Comment by T-nfd** [comment]
Dear @smandelli,

Thank you for your answer. As a final question, can you help me please how can I download the Dresden dataset? 
 Unfortunatky, the main links doesn't work:
 
http://forensics.inf.tu-dresden.de/ddimgdb/
http://forensics.inf.tu-dresden.de/dresden_image_database/

I have been looking for it for a long time. Do you have an active link?

**Comment by T-nfd** [comment]
Dear @smandelli, Do you have any active links to this dataset?

**Comment by smandelli** [comment]
Hi @T-nfd, unfortunately I don't have a link for downloading the dataset. 
If you necessarily need the Dresden database, you may try to contact the authors of the paper. Otherwise, I would suggest you to download some newly released datasets like the Vision, the Forchheim, etc.

**Comment by T-nfd** [comment]
Dear @smandelli, Thanks for your reply.
I contacted the authors long ago, but unfortunately, I have not received any reply yet.
I've downloaded Vision as an alternative, but I wanted to use the Dresden dataset for future comparisons because most papers have used this dataset.
Thanks again for your patience in replying.

**Comment by mandelli** [comment]
Dear all,
I think you write to the wrong person. In GitHub is mentioned Sara Mandelli.I’m not Sara.
&#128522;
Ciao


[https://web.meisystem.com/images/firma.jpg]    Filippo Mandelli
SW Development Supervisor
SW Development Dept.
Office +39 035 339112
Email  ***@***.***
MS Teams start ***@***.***>         MEI s.r.l.
Via Ing. Caproni, 50
24036 Ponte San Pietro (BG)
T +39 035 339112     F +39 035 4378007
www.meisystem.com<https://meisystem.com/>
[https://web.meisystem.com/img/facebook.jpg]<https://www.facebook.com/meieasyfittrend>  [https://web.meisystem.com/img/linkedin.jpg] <https://it.linkedin.com/company/mei-srl>  [https://web.meisystem.com/img/youtube.jpg] <https://www.youtube.com/user/MeiSrl>       [https://web.meisystem.com/img/instagram.jpg] <https://www.instagram.com/meieasyfittrend_lensedger/>


Da: T-nfd ***@***.***>
Inviato: sabato 11 marzo 2023 07:46
A: polimi-ispl/cnn-fast-sdi ***@***.***>
Cc: Filippo Mandelli ***@***.***>; Mention ***@***.***>
Oggetto: Re: [polimi-ispl/cnn-fast-sdi] prnu extarction (Issue #3)

This email is from an unusual correspondent. Make sure this is someone you trust.


Dear @mandelli<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fmandelli&e=2730512d&h=1ee66107&f=y&p=n>, Thanks for your reply.
I contacted the authors long ago, but unfortunately, I have not received any reply yet.
I've downloaded Vision as an alternative, but I wanted to use the Dresden dataset for future comparisons because most papers have used this dataset.
Thanks again for your patience in replying.

**Comment by T-nfd** [comment]
Dear @mandelli, my bad, sorry. I edited.
